export {
  canAccessCoreDatabase,
  getDatabaseScopedIdentity,
  hasDatabaseCapability,
} from "./access";
export { CoreClient, createCoreClient } from "./client";
export {
  type CoreClientConfig,
  type DashboardApiKeysStorageConfig,
  type DashboardAuthStorageConfig,
  type DashboardProjectsStorageConfig,
  getCoreApiBaseUrl,
  getCoreClientConfig,
  getDashboardApiKeysStorageConfig,
  getDashboardAuthStorageConfig,
  getDashboardProjectsStorageConfig,
  normalizeCoreBaseUrl,
} from "./config";
export { CoreApiError, isCoreApiError } from "./errors";
export {
  validateCoreCollectionName,
  validateCoreDatabaseName,
  validateCoreFieldName,
  validateCoreNameSegment,
} from "./names";
export {
  createProjectAdminToken,
  createProjectCoreClient,
  getProjectCoreClientConfig,
} from "./project-client";
export type {
  Capability,
  CoreDocument,
  CoreIndexInfo,
  CoreIndexState,
  CoreRequestOptions,
  CreateApiKeyParams,
  CreateApiKeyResult,
  CreateCollectionParams,
  CreateCollectionResult,
  CreateDocumentParams,
  CreateIndexParams,
  CreateIndexResult,
  DeleteCollectionParams,
  DeleteCollectionResult,
  DeleteDocumentParams,
  DeleteIndexParams,
  DeleteIndexResult,
  DeleteSchemaParams,
  DeleteSchemaResult,
  GetDocumentParams,
  GetSchemaParams,
  ListCollectionsParams,
  ListDocumentsParams,
  ListDocumentsResult,
  ListIndexesParams,
  ListIndexesResult,
  MeResponse,
  RuntimeApiKeyScope,
  Scope,
  SetSchemaParams,
  SetSchemaResult,
  UpdateDocumentParams,
  ValidateSchemaParams,
  ValidateSchemaResult,
} from "./types";
